# Generated by Django 2.2.6 on 2020-02-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsInfo',
            fields=[
                ('method_id', models.IntegerField(default=1000, primary_key=True, serialize=False, verbose_name='方法编号')),
                ('method_name', models.CharField(max_length=50, verbose_name='方法名称')),
                ('method_type', models.CharField(choices=[('For RNAseq data', 'RNAseq数据'), ('For Probe data', '探针数据')], default='For RNAseq data', max_length=20, verbose_name='方法类型')),
                ('method_detail', models.TextField(verbose_name='方法详情')),
                ('author', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='作者名称')),
                ('args', models.CharField(blank=True, max_length=80, null=True, verbose_name='常用参数')),
                ('use_number', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '筛选方法',
                'verbose_name_plural': '筛选方法',
            },
        ),
    ]
