# Generated by Django 2.2.6 on 2020-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsinfo',
            name='method_type',
            field=models.CharField(choices=[('With Select Tag', '有筛选指标'), ('No Select Tag', '无筛选指标')], default='With Select Tag', max_length=20, verbose_name='方法类型'),
        ),
    ]
