# Generated by Django 2.2.6 on 2020-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='method_id',
            field=models.CharField(default='1001', max_length=10, verbose_name='方法编号'),
        ),
    ]
