# Generated by Django 2.2.6 on 2020-02-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20200205_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='birday',
        ),
    ]
