# Generated by Django 2.2.6 on 2020-02-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20200218_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
